/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sitwarehouse.ConnectionBuilder;
import static sitwarehouse.Member.*;
import static sitwarehouse.Employee.*;
import sitwarehouse.Member;
import sitwarehouse.SITOperation;
import sitwarehouse.Warehouse;

/**
 *
 * @author Superz
 */
public class SITwarehouse extends javax.swing.JFrame {

    /**
     * Creates new form SITwarehouse
     */
    public SITwarehouse() {
        initComponents();

    }

    public void closeToLogin() {
        Container.removeAll();
        Container.repaint();
        Container.revalidate();
        accId.setText("");
        accPass.setText("");
        cfAccPass.setText("");
        name.setText("");
        address.setText("");
        phoneNumber.setText("");
        Container.add(Login);
        Container.repaint();
        Container.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFrame1 = new javax.swing.JFrame();
        Container = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        userType = new javax.swing.JComboBox();
        passWord = new javax.swing.JPasswordField();
        bgRegister1 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        accId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        backLogin = new javax.swing.JButton();
        Chackpass = new javax.swing.JLabel();
        accPass = new javax.swing.JPasswordField();
        cfAccPass = new javax.swing.JPasswordField();
        jScrollPane9 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextPane();
        bgRegister = new javax.swing.JLabel();
        MemberHome = new javax.swing.JPanel();
        HelloMember = new javax.swing.JLabel();
        dateMemHome = new javax.swing.JLabel();
        memIdGui = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mbTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        AgrMem = new javax.swing.JButton();
        bgMem = new javax.swing.JLabel();
        EmployeeHome = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        empIdGui = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        dateEmpHome = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        emTable = new javax.swing.JTable();
        bgEm4 = new javax.swing.JLabel();
        EditProfile = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        backLogin1 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        phoneNumber1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        accId1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address1 = new javax.swing.JTextPane();
        oldPassword = new javax.swing.JPasswordField();
        accPass1 = new javax.swing.JPasswordField();
        bgMem1 = new javax.swing.JLabel();
        ListOfWarehouseMember = new javax.swing.JPanel();
        backLogin2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        textSeach = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        listSearch = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        listMbTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        bgMem2 = new javax.swing.JLabel();
        EditWarehouse = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        backLogin4 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        editWhPrice = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        editWhId = new javax.swing.JTextField();
        editWhStatus = new javax.swing.JComboBox<>();
        bgEm3 = new javax.swing.JLabel();
        ListOfPermission = new javax.swing.JPanel();
        backLogin5 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablePMS = new javax.swing.JTable();
        tagSearch = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        SearchPms = new javax.swing.JTextField();
        SelectPms = new javax.swing.JComboBox<>();
        bgEm2 = new javax.swing.JLabel();
        CreatePermission = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        agreementId = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        money = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        bankNo = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        listBank = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        SubmitBank = new javax.swing.JButton();
        backLogin6 = new javax.swing.JButton();
        bgMem4 = new javax.swing.JLabel();
        ListAgreement = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableAgrMem = new javax.swing.JTable();
        backLogin7 = new javax.swing.JButton();
        bgMem3 = new javax.swing.JLabel();
        ListOfWarehouseEmployee = new javax.swing.JPanel();
        backLogin3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        textSeachEM = new javax.swing.JTextField();
        listSearchEM = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        whIdEdit = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        listEmTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        bgEm5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setLayout(new java.awt.CardLayout());

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Welcome");
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 128, -1, -1));

        jLabel2.setText("Username");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 226, 90, -1));

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        Login.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 255, 200, -1));

        jLabel3.setText("Password");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 290, 90, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        Login.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 353, 79, 35));

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        Login.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 395, -1, -1));

        userType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Member", "Employee" }));
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });
        Login.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 190, -1, -1));
        Login.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 313, 200, -1));

        bgRegister1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/google_abstract_hd.jpg"))); // NOI18N
        Login.add(bgRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-710, -310, 1910, 1030));

        Container.add(Login, "card2");

        Register.setBackground(new java.awt.Color(255, 204, 255));
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Register");
        Register.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 50, -1, -1));

        accId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accIdActionPerformed(evt);
            }
        });
        Register.add(accId, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 134, 200, -1));

        jLabel5.setText("Username");
        Register.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 112, -1, 9));

        jLabel6.setText("Password");
        Register.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 157, -1, -1));

        jLabel7.setText("Confirm Password");
        Register.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 209, -1, -1));

        jLabel8.setText("Name and Surname");
        Register.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 261, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        Register.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 284, 200, -1));

        jLabel9.setText("Address");
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 313, -1, -1));

        jLabel10.setText("Phone Number");
        Register.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 415, -1, -1));

        if(phoneNumber.getText().length() == 3){
            phoneNumber.setEnabled(false);
        }else{
            phoneNumber.setEnabled(true);
        }
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberNumberActionPerformed(evt);
            }
        });
        Register.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 444, 200, -1));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        Register.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 482, -1, 35));

        backLogin.setText("< Back");
        backLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginActionPerformed(evt);
            }
        });
        Register.add(backLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 69, -1, -1));
        Register.add(Chackpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 524, 293, -1));
        Register.add(accPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 180, 200, -1));

        cfAccPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfAccPassActionPerformed(evt);
            }
        });
        Register.add(cfAccPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 232, 200, -1));

        jScrollPane9.setViewportView(address);

        Register.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 336, 200, 72));

        bgRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/google_abstract_hd.jpg"))); // NOI18N
        Register.add(bgRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1110, -310, 1910, 1030));

        Container.add(Register, "card3");

        MemberHome.setBackground(new java.awt.Color(255, 204, 255));
        MemberHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HelloMember.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        HelloMember.setText("Hello");
        MemberHome.add(HelloMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 56, 236, -1));

        dateMemHome.setText("Date: ");
        MemberHome.add(dateMemHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 131, -1, -1));

        memIdGui.setText("Member ID: ");
        MemberHome.add(memIdGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 99, -1, -1));

        jButton1.setText("Buy");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MemberHome.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 63, -1, -1));

        jButton2.setText("Confirm Money Transfer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        MemberHome.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 127, -1, -1));

        mbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SIZE", "PRICE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mbTable.setToolTipText("");
        mbTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mbTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(mbTable);

        MemberHome.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 244, 571, 305));

        jLabel14.setText("Your warehouse");
        MemberHome.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 210, -1, -1));

        Edit.setText("Edit Profile");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        MemberHome.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 95, -1, -1));

        logOut.setText("Logout");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        MemberHome.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 159, -1, -1));
        MemberHome.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 56, 120, 19));

        AgrMem.setText("Agreement");
        AgrMem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgrMemMouseClicked(evt);
            }
        });
        MemberHome.add(AgrMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 159, -1, -1));

        bgMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/abstract_wallpaper_best_background_3009_high_quality.jpg"))); // NOI18N
        MemberHome.add(bgMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 1020, 750));

        Container.add(MemberHome, "card4");

        EmployeeHome.setBackground(new java.awt.Color(255, 204, 255));
        EmployeeHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Check Transaction");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        EmployeeHome.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Adminstrator");
        EmployeeHome.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 56, -1, -1));

        empIdGui.setText("Employee ID:");
        EmployeeHome.add(empIdGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 92, -1, -1));

        jButton4.setText("Edit Warehouse Profile");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        EmployeeHome.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        dateEmpHome.setText("Date: ");
        EmployeeHome.add(dateEmpHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 134, -1, -1));

        jLabel18.setText("List of Member");
        EmployeeHome.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 166, -1, -1));

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        EmployeeHome.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 85, -1));

        emTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Account ID", "Name", "Address", "Phonenumber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        emTable.setToolTipText("");
        emTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                emTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane8.setViewportView(emTable);

        EmployeeHome.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 570, 270));

        bgEm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/figura.png"))); // NOI18N
        EmployeeHome.add(bgEm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 840, 630));

        Container.add(EmployeeHome, "card5");

        EditProfile.setBackground(new java.awt.Color(255, 204, 255));
        EditProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Edit Profile");
        EditProfile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 48, -1, -1));

        backLogin1.setText("< Back");
        backLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin1ActionPerformed(evt);
            }
        });
        EditProfile.add(backLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 48, -1, -1));

        submit1.setText("Submit");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        EditProfile.add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 517, 76, 39));

        phoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumber1NumberActionPerformed(evt);
            }
        });
        EditProfile.add(phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 412, 200, -1));

        jLabel20.setText("Phone Number");
        EditProfile.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 385, -1, -1));

        jLabel21.setText("Address");
        EditProfile.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 279, -1, -1));

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        EditProfile.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 244, 200, -1));

        jLabel22.setText("Name and Surname");
        EditProfile.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 215, -1, -1));

        jLabel24.setText("New Password");
        EditProfile.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 157, -1, -1));

        jLabel25.setText("Username");
        EditProfile.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 105, -1, -1));

        accId1.setEditable(false);
        accId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accId1ActionPerformed(evt);
            }
        });
        EditProfile.add(accId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 128, 200, -1));

        jLabel52.setText("Password");
        EditProfile.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 447, -1, -1));

        jScrollPane1.setViewportView(address1);

        EditProfile.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 302, 200, 70));
        EditProfile.add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 476, 200, -1));
        EditProfile.add(accPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 180, 200, -1));

        bgMem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/abstract_wallpaper_best_background_3009_high_quality.jpg"))); // NOI18N
        EditProfile.add(bgMem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 1020, 750));

        Container.add(EditProfile, "card6");

        ListOfWarehouseMember.setBackground(new java.awt.Color(255, 204, 255));
        ListOfWarehouseMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backLogin2.setText("< Back");
        backLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogin2MouseClicked(evt);
            }
        });
        backLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin2ActionPerformed(evt);
            }
        });
        ListOfWarehouseMember.add(backLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("List of Available Warehouse");
        ListOfWarehouseMember.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 53));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        ListOfWarehouseMember.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, -1, -1));

        textSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSeachActionPerformed(evt);
            }
        });
        ListOfWarehouseMember.add(textSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 100, -1));

        jLabel41.setText("Search by:");
        ListOfWarehouseMember.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        listSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warehouse ID", "Price", "Size" }));
        listSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSearchActionPerformed(evt);
            }
        });
        ListOfWarehouseMember.add(listSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 120, -1));

        listMbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SIZE", "PRICE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listMbTable.setToolTipText("");
        listMbTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listMbTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listMbTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane10.setViewportView(listMbTable);

        ListOfWarehouseMember.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 571, 305));

        jButton5.setText("See All");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ListOfWarehouseMember.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 471, 84, -1));

        bgMem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/abstract_wallpaper_best_background_3009_high_quality.jpg"))); // NOI18N
        ListOfWarehouseMember.add(bgMem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 1020, 750));

        Container.add(ListOfWarehouseMember, "card7");

        EditWarehouse.setBackground(new java.awt.Color(255, 204, 255));
        EditWarehouse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel30.setText("Edit");
        EditWarehouse.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 48, -1, -1));

        backLogin4.setText("< Back");
        backLogin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin4ActionPerformed(evt);
            }
        });
        EditWarehouse.add(backLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 67, -1, -1));

        submit2.setText("Submit");
        EditWarehouse.add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 294, -1, -1));

        jLabel34.setText("Status");
        EditWarehouse.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 214, -1, -1));

        editWhPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWhPriceActionPerformed(evt);
            }
        });
        EditWarehouse.add(editWhPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 185, 200, -1));

        jLabel35.setText("Price");
        EditWarehouse.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 162, -1, -1));

        jLabel36.setText("Warehouse ID");
        EditWarehouse.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 110, -1, -1));

        editWhId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWhIdActionPerformed(evt);
            }
        });
        EditWarehouse.add(editWhId, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 133, 200, -1));

        editWhStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STANDBY", "IN USE", "MAINTENANCE" }));
        EditWarehouse.add(editWhStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 243, 200, -1));

        bgEm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/figura.png"))); // NOI18N
        EditWarehouse.add(bgEm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 840, 630));

        Container.add(EditWarehouse, "card8");

        ListOfPermission.setBackground(new java.awt.Color(255, 204, 255));
        ListOfPermission.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backLogin5.setText("< Back");
        backLogin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogin5MouseClicked(evt);
            }
        });
        backLogin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin5ActionPerformed(evt);
            }
        });
        ListOfPermission.add(backLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 65, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel42.setText("List of Permission");
        ListOfPermission.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        TablePMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PermissionID", "AgreementID", "PaidDate", "PaidMount", "Ischeck", "BamkName", "BankID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablePMS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablePMSAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(TablePMS);

        ListOfPermission.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 694, 287));

        tagSearch.setText("Search");
        tagSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagSearchActionPerformed(evt);
            }
        });
        ListOfPermission.add(tagSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        jLabel45.setText("Search by:");
        ListOfPermission.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        SearchPms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPmsActionPerformed(evt);
            }
        });
        ListOfPermission.add(SearchPms, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 100, -1));

        SelectPms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permission ID", "Agreement ID", " " }));
        ListOfPermission.add(SelectPms, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 130, -1));

        bgEm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/figura.png"))); // NOI18N
        ListOfPermission.add(bgEm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 840, 630));

        Container.add(ListOfPermission, "card10");

        CreatePermission.setBackground(new java.awt.Color(255, 204, 255));
        CreatePermission.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel46.setText("Report the money transfer");
        CreatePermission.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 64, -1, -1));

        jLabel47.setText("Transfer Date:");
        CreatePermission.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 169, -1, -1));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CreatePermission.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 166, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        CreatePermission.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 166, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2559", "2560", "2561", "2562", "2563", "2564", "2565" }));
        CreatePermission.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 166, 70, -1));
        CreatePermission.add(agreementId, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 126, 176, -1));

        jLabel48.setText("Agreement ID:");
        CreatePermission.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 126, -1, -1));
        CreatePermission.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 206, 176, -1));

        jLabel49.setText("Amount of Money:");
        CreatePermission.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 206, -1, -1));
        CreatePermission.add(bankNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 286, 176, -1));

        jLabel50.setText("Bank:");
        CreatePermission.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 246, -1, -1));

        listBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasikorn", "Krungthep", "Thaipanit", "Krungthai", "Issaram" }));
        CreatePermission.add(listBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 246, 176, -1));

        jLabel51.setText("Bank account No:");
        CreatePermission.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 286, -1, -1));

        SubmitBank.setText("Submit");
        CreatePermission.add(SubmitBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 336, 94, 38));

        backLogin6.setText("< Back");
        backLogin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogin6MouseClicked(evt);
            }
        });
        backLogin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin6ActionPerformed(evt);
            }
        });
        CreatePermission.add(backLogin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 75, -1, -1));

        bgMem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/abstract_wallpaper_best_background_3009_high_quality.jpg"))); // NOI18N
        CreatePermission.add(bgMem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 1020, 750));

        Container.add(CreatePermission, "card11");

        ListAgreement.setBackground(new java.awt.Color(255, 204, 255));
        ListAgreement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Agreement Member");
        ListAgreement.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 61, -1, -1));

        TableAgrMem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AmId", "MemId", "WhId", "TotalDepts", "StartDate", "EndDate", "NpaidDate", "Arrears", "Npaid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableAgrMem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TableAgrMemAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(TableAgrMem);

        ListAgreement.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 139, 694, 390));

        backLogin7.setText("< Back");
        backLogin7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogin7MouseClicked(evt);
            }
        });
        backLogin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin7ActionPerformed(evt);
            }
        });
        ListAgreement.add(backLogin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 61, -1, -1));

        bgMem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/abstract_wallpaper_best_background_3009_high_quality.jpg"))); // NOI18N
        ListAgreement.add(bgMem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -120, 1020, 750));

        Container.add(ListAgreement, "card2");

        ListOfWarehouseEmployee.setBackground(new java.awt.Color(255, 204, 255));
        ListOfWarehouseEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backLogin3.setText("< Back");
        backLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLogin3MouseClicked(evt);
            }
        });
        ListOfWarehouseEmployee.add(backLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 65, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setText("List of Warehouse");
        ListOfWarehouseEmployee.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jButton8.setText("Search");
        ListOfWarehouseEmployee.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jLabel37.setText("Search by:");
        ListOfWarehouseEmployee.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));
        ListOfWarehouseEmployee.add(textSeachEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 100, -1));

        listSearchEM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warehouse ID", "Price", "Size" }));
        ListOfWarehouseEmployee.add(listSearchEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 128, -1));

        jLabel38.setText("Warehouse ID:");
        ListOfWarehouseEmployee.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));
        ListOfWarehouseEmployee.add(whIdEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 100, -1));

        jButton11.setText("Edit");
        ListOfWarehouseEmployee.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 70, -1));

        listEmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SIZE", "PRICE", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listEmTable.setToolTipText("");
        listEmTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listEmTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane11.setViewportView(listEmTable);

        ListOfWarehouseEmployee.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 128, 571, 305));

        jButton6.setText("See All");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ListOfWarehouseEmployee.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 84, -1));

        bgEm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/figura.png"))); // NOI18N
        ListOfWarehouseEmployee.add(bgEm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 840, 630));

        Container.add(ListOfWarehouseEmployee, "card12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accIdActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void phoneNumberNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberNumberActionPerformed

    private void backLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginActionPerformed
        Register.setVisible(false);

        accId.setText("");
        accPass.setText("");
        cfAccPass.setText("");
        name.setText("");
        address.setText("");
        phoneNumber.setText("");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));

        Login.setVisible(true);
    }//GEN-LAST:event_backLoginActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Login.setVisible(false);
        Register.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed

        accId1.setText(SITOperation.mem.getAccId());
        name1.setText(SITOperation.mem.getName());
        address1.setText(SITOperation.mem.getAddress());
        phoneNumber1.setText(SITOperation.mem.getPhoneNumber());

    }//GEN-LAST:event_EditActionPerformed

    private void backLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin1ActionPerformed
        // TODO add your handling code here:
        EditProfile.setVisible(false);
        MemberHome.setVisible(true);
    }//GEN-LAST:event_backLogin1ActionPerformed

    private void phoneNumber1NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumber1NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumber1NumberActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void accId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accId1ActionPerformed

    private void backLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_backLogin2ActionPerformed

    private void backLogin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin4ActionPerformed
        EditWarehouse.setVisible(false);
        ListOfWarehouseEmployee.setVisible(true);
    }//GEN-LAST:event_backLogin4ActionPerformed

    private void editWhPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWhPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editWhPriceActionPerformed

    private void editWhIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWhIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editWhIdActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) listMbTable.getModel();
            String list = (String) listSearch.getSelectedItem();
            String text = textSeach.getText().toUpperCase();
            if (list.equalsIgnoreCase("Warehouse ID")) {
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM WAREHOUSE WHERE WAREHOUSEID=" + text;
                ResultSet rs = stmt.executeQuery(SQL);
                model.setNumRows(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                }
            } else if (list.equalsIgnoreCase("Price")) {
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM WAREHOUSE WHERE PRICE=" + text;
                ResultSet rs = stmt.executeQuery(SQL);
                model.setNumRows(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                }
            } else {
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM WAREHOUSE WHERE SIZE='" + text + "'";
                ResultSet rs = stmt.executeQuery(SQL);
                model.setNumRows(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                }
            }
        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void textSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSeachActionPerformed

    private void backLogin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablePMS.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_backLogin5ActionPerformed

    private void SearchPmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPmsActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        String nameString = name.getText();
        String addressString = address.getText();
        String phoneNumberString = phoneNumber.getText();
        String accIdString = accId.getText();
        String accPassString = new String(accPass.getPassword());
        String cfPasswordString = new String(cfAccPass.getPassword());

        if (name.getText().equalsIgnoreCase("") || this.address.getText().equalsIgnoreCase("") || this.phoneNumber.getText().equalsIgnoreCase("")
                || accId.getText().equalsIgnoreCase(" ") || accPassString.equalsIgnoreCase("") || cfPasswordString.equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "Please , Enter all the fields.");
        } else if (cfPasswordString.equals(accPassString)) {
            Pattern p = Pattern.compile("\\d+");
            Matcher m = p.matcher(phoneNumberString);
            boolean isNumber = m.matches();
            if (isNumber) {
                create(nameString, addressString, phoneNumberString, accIdString, accPassString);
                JOptionPane.showMessageDialog(null, "Register Successfully.");
                jLabel6.setForeground(new java.awt.Color(0, 0, 0));
                jLabel7.setForeground(new java.awt.Color(0, 0, 0));
                jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                closeToLogin();
            } else {
                jLabel10.setForeground(new java.awt.Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Please ENTER REAL PHONE NUMBER.");
            }
        } else {
            jLabel6.setForeground(new java.awt.Color(255, 0, 0));
            jLabel7.setForeground(new java.awt.Color(255, 0, 0));
            JOptionPane.showMessageDialog(null, "Password and Comfirm Password is not the same.");
        }

    }//GEN-LAST:event_submitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String userTypeStr = (String) userType.getSelectedItem();
        String userNameString = userName.getText();
        String passString = new String(passWord.getPassword());

        Date today = new Date();
        String todayString = today.toString();

        if (SITOperation.login(userNameString, passString, userTypeStr)) {
            if (userTypeStr.equalsIgnoreCase("employee")) {
                Login.setVisible(false);
                empIdGui.setText("Employee ID: " + SITOperation.em.getEmId());
                dateEmpHome.setText("Date: " + todayString);
                EmployeeHome.setVisible(true);
            } else {
                Login.setVisible(false);
                HelloMember.setText("Hello " + SITOperation.mem.getName());
                memIdGui.setText("Member ID: " + SITOperation.mem.getMemId());
                dateMemHome.setText("Date: " + todayString);
                MemberHome.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username or Password is wrong, Please try again or contect adminstator." + userTypeStr);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeActionPerformed

    private void cfAccPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfAccPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cfAccPassActionPerformed

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        // TODO add your handling code here:
        this.MemberHome.setVisible(false);
        this.EditProfile.setVisible(true);


    }//GEN-LAST:event_EditMouseClicked

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed

        Pattern p = Pattern.compile("\\d+");
        Matcher m = p.matcher(phoneNumber1.getText());
        boolean isNumber = m.matches();
        if (isNumber) {
            if (accPass1.getText().equalsIgnoreCase("")) {
                if (Member.edit(name1.getText(), address1.getText(), phoneNumber1.getText(), oldPassword.getText(), SITOperation.mem.getMemId(), accPass1.getText())) {
                    JOptionPane.showMessageDialog(null, "Update Profile Successfully.");
                    jLabel52.setForeground(new java.awt.Color(0, 0, 0));
                    jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                    EditProfile.setVisible(false);
                    oldPassword.setText("");
                    HelloMember.setText("Hello " + name1.getText());
                    MemberHome.setVisible(true);
                } else {
                    jLabel52.setForeground(new java.awt.Color(255, 0, 0));
                    JOptionPane.showMessageDialog(null, "Your password is wrong.");
                }
            } else {
                if (Member.edit(name1.getText(), address1.getText(), phoneNumber1.getText(), oldPassword.getText(), SITOperation.mem.getMemId(), accPass1.getText())) {
                    JOptionPane.showMessageDialog(null, "Update Profile Successfully.");
                    jLabel52.setForeground(new java.awt.Color(0, 0, 0));
                    jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                    EditProfile.setVisible(false);
                    oldPassword.setText("");
                    accPass1.setText("");
                    HelloMember.setText("Hello " + name1.getText());
                    MemberHome.setVisible(true);
                } else {
                    jLabel52.setForeground(new java.awt.Color(255, 0, 0));
                    JOptionPane.showMessageDialog(null, "Your password is wrong.");
                }
            }
        } else {
            jLabel10.setForeground(new java.awt.Color(255, 0, 0));
            JOptionPane.showMessageDialog(null, "Please ENTER REAL PHONE NUMBER.");
        }
    }//GEN-LAST:event_submit1ActionPerformed

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        SITOperation.logout("member");
        MemberHome.setVisible(false);
        userName.setText("");
        passWord.setText("");
        Login.setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.MemberHome.setVisible(false);
        this.ListOfWarehouseMember.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void backLogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogin2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listMbTable.getModel();
        this.ListOfWarehouseMember.setVisible(false);
        this.MemberHome.setVisible(true);
        textSeach.setText("");
        listSearch.setActionCommand("Warehouse ID");
        model.setNumRows(0);
    }//GEN-LAST:event_backLogin2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        this.EmployeeHome.setVisible(false);
        this.ListOfWarehouseEmployee.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        DefaultTableModel model = (DefaultTableModel) emTable.getModel();
        model.setNumRows(0);
         SITOperation.logout("employee");
        EmployeeHome.setVisible(false);
        Login.setVisible(true);
         userName.setText("");
        passWord.setText("");
    }//GEN-LAST:event_logoutMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        this.EmployeeHome.setVisible(false);
        this.ListOfPermission.setVisible(true);
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void backLogin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backLogin6ActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

    }//GEN-LAST:event_logOutActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

    }//GEN-LAST:event_logoutActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mbTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mbTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mbTableAncestorAdded

    private void listMbTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listMbTableAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) listMbTable.getModel();
        try {
            Connection cnb = ConnectionBuilder.connect();
            Statement stmt = cnb.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MYDB.WAREHOUSE");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            cnb.close();

        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }

    }//GEN-LAST:event_listMbTableAncestorAdded

    private void backLogin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogin5MouseClicked
         DefaultTableModel model1 = (DefaultTableModel)TablePMS.getModel();
         model1.setNumRows(0);
         DefaultTableModel model2 = (DefaultTableModel) emTable.getModel();
         model2.setNumRows(0);
         ListOfPermission.setVisible(false);
         EmployeeHome.setVisible(true);
        
        // TablePMS.setToolTipText("");
    }//GEN-LAST:event_backLogin5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        MemberHome.setVisible(false);
        CreatePermission.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void backLogin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogin6MouseClicked
        CreatePermission.setVisible(false);
        agreementId.setText("");
        day.setSelectedItem("01");
        month.setSelectedItem("01");
        year.setSelectedItem("2559");
        money.setText("");
        listBank.setSelectedItem("Kasikorn");
        bankNo.setText("");
        MemberHome.setVisible(true);
    }//GEN-LAST:event_backLogin6MouseClicked

    private void listSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSearchActionPerformed

    private void TablePMSAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablePMSAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TablePMS.getModel();
        try {
            Connection cnb = ConnectionBuilder.connect();
            Statement stmt = cnb.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MYDB.PERMISSION");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
            cnb.close();

        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }

    }//GEN-LAST:event_TablePMSAncestorAdded

    private void tagSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagSearchActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) TablePMS.getModel();
            String list = (String) SelectPms.getSelectedItem();
            String text = SearchPms.getText().toUpperCase();
            if (list.equalsIgnoreCase("Permission ID")) {
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM PERMISSION WHERE PERMISSIONID=" + text;
                ResultSet rs = stmt.executeQuery(SQL);
                model.setNumRows(0);
                while (rs.next()) {

                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});

                }
            } else if (list.equalsIgnoreCase("Agreement ID")) {
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM PERMISSION WHERE AGREEMENTID=" + text;
                ResultSet rs = stmt.executeQuery(SQL);
                model.setNumRows(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                }
            }
        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }
    }//GEN-LAST:event_tagSearchActionPerformed

    private void backLogin7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogin7MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) TableAgrMem.getModel();
        ListAgreement.setVisible(false);
        MemberHome.setVisible(true);
        model.setNumRows(0);
     //   TableAgrMem.setrow
    }//GEN-LAST:event_backLogin7MouseClicked

    private void backLogin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backLogin7ActionPerformed

    private void TableAgrMemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableAgrMemAncestorAdded
       
        try {
            DefaultTableModel model = (DefaultTableModel) TableAgrMem.getModel();
                Connection cnb = ConnectionBuilder.connect();
                Statement stmt = cnb.createStatement();
                String SQL = "SELECT * FROM AGREEMENT WHERE MEMID="+ SITOperation.mem.getMemId();
                ResultSet rs = stmt.executeQuery(SQL);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4), 
                        rs.getString(5), rs.getString(6), rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }
    }//GEN-LAST:event_TableAgrMemAncestorAdded

    private void AgrMemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgrMemMouseClicked
        // TODO add your handling code here:
        this.MemberHome.setVisible(false);
        ListAgreement.setVisible(true);
    }//GEN-LAST:event_AgrMemMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultTableModel model = (DefaultTableModel) listMbTable.getModel();
        this.ListOfWarehouseMember.setVisible(false);
        this.ListOfWarehouseMember.setVisible(true);
        textSeach.setText("");
        model.setNumRows(0);
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void emTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_emTableAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel models = (DefaultTableModel) emTable.getModel();
        try {
            Connection cnb = ConnectionBuilder.connect();
            Statement stmt = cnb.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT MEMID,ACCID,MEMNAME,MEMADDRESS,MEMPHONENUMBER FROM MYDB.MEMBER");
            while (rs.next()) {
                models.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4),rs.getString(5)});
            }
            cnb.close();

        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }

    }//GEN-LAST:event_emTableAncestorAdded

    private void backLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLogin3MouseClicked
        DefaultTableModel model1 = (DefaultTableModel) listMbTable.getModel();
        this.ListOfWarehouseEmployee.setVisible(false);
        this.EmployeeHome.setVisible(true);
        textSeachEM.setText("");
        listSearchEM.setActionCommand("Warehouse ID");
        model1.setNumRows(0);
        DefaultTableModel model2 = (DefaultTableModel) emTable.getModel();
        model2.setNumRows(0);
    }//GEN-LAST:event_backLogin3MouseClicked

    private void listEmTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listEmTableAncestorAdded
        DefaultTableModel model = (DefaultTableModel) listEmTable.getModel();
        try {
            Connection cnb = ConnectionBuilder.connect();
            Statement stmt = cnb.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MYDB.WAREHOUSE");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            cnb.close();

        } catch (SQLException err) {
            System.out.print(err);
        } catch (ClassNotFoundException err) {
            System.out.print(err);
        }
    }//GEN-LAST:event_listEmTableAncestorAdded

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        DefaultTableModel model = (DefaultTableModel) listEmTable.getModel();
        this.ListOfWarehouseEmployee.setVisible(false);
        this.ListOfWarehouseEmployee.setVisible(true);
        textSeachEM.setText("");
        model.setNumRows(0);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SITwarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SITwarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SITwarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SITwarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SITwarehouse Jframe = new SITwarehouse();
                Jframe.setVisible(true);
                Jframe.setSize(800, 600);
                Jframe.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgrMem;
    private javax.swing.JLabel Chackpass;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel CreatePermission;
    private javax.swing.JButton Edit;
    private javax.swing.JPanel EditProfile;
    private javax.swing.JPanel EditWarehouse;
    private javax.swing.JPanel EmployeeHome;
    private javax.swing.JLabel HelloMember;
    private javax.swing.JPanel ListAgreement;
    private javax.swing.JPanel ListOfPermission;
    private javax.swing.JPanel ListOfWarehouseEmployee;
    private javax.swing.JPanel ListOfWarehouseMember;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MemberHome;
    private javax.swing.JPanel Register;
    private javax.swing.JTextField SearchPms;
    private javax.swing.JComboBox<String> SelectPms;
    private javax.swing.JButton SubmitBank;
    private javax.swing.JTable TableAgrMem;
    private javax.swing.JTable TablePMS;
    private javax.swing.JTextField accId;
    private javax.swing.JTextField accId1;
    private javax.swing.JPasswordField accPass;
    private javax.swing.JPasswordField accPass1;
    private javax.swing.JTextPane address;
    private javax.swing.JTextPane address1;
    private javax.swing.JTextField agreementId;
    private javax.swing.JButton backLogin;
    private javax.swing.JButton backLogin1;
    private javax.swing.JButton backLogin2;
    private javax.swing.JButton backLogin3;
    private javax.swing.JButton backLogin4;
    private javax.swing.JButton backLogin5;
    private javax.swing.JButton backLogin6;
    private javax.swing.JButton backLogin7;
    private javax.swing.JTextField bankNo;
    private javax.swing.JLabel bgEm2;
    private javax.swing.JLabel bgEm3;
    private javax.swing.JLabel bgEm4;
    private javax.swing.JLabel bgEm5;
    private javax.swing.JLabel bgMem;
    private javax.swing.JLabel bgMem1;
    private javax.swing.JLabel bgMem2;
    private javax.swing.JLabel bgMem3;
    private javax.swing.JLabel bgMem4;
    private javax.swing.JLabel bgRegister;
    private javax.swing.JLabel bgRegister1;
    private javax.swing.JPasswordField cfAccPass;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateEmpHome;
    private javax.swing.JLabel dateMemHome;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField editWhId;
    private javax.swing.JTextField editWhPrice;
    private javax.swing.JComboBox<String> editWhStatus;
    private javax.swing.JTable emTable;
    private javax.swing.JLabel empIdGui;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> listBank;
    private javax.swing.JTable listEmTable;
    private javax.swing.JTable listMbTable;
    private javax.swing.JComboBox<String> listSearch;
    private javax.swing.JComboBox<String> listSearchEM;
    private javax.swing.JButton logOut;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JTable mbTable;
    private javax.swing.JLabel memIdGui;
    private javax.swing.JTextField money;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField phoneNumber1;
    private javax.swing.JButton register;
    private javax.swing.JButton search;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit2;
    private javax.swing.JButton tagSearch;
    private javax.swing.JTextField textSeach;
    private javax.swing.JTextField textSeachEM;
    private javax.swing.JTextField userName;
    private javax.swing.JComboBox userType;
    private javax.swing.JTextField whIdEdit;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
